import random


def input_number(min, max):
    """Takes two number as input one is maximum and other is minimum and return random integer number with these two input
    
    Parameters
    ----------
    min : int
        Stores the minimum number input by user
    max : int
        Stores the maximum number input by user

    Returns
    -------
    int
        A int is return in the specified range of min and max
    """
    return random.randint(min, max)


def choose_sign():
    """Function return a mathematical operation sign randomly

    Returns
    -------
    str
        A random mathematical sign return from the array  
    """
    return random.choice(['+', '-', '*'])


def apply_operation(n1, n2, o):
    """Takes two number as input both of them are operand and finally takes operator 

    Parameters
    ----------
    n1 : int
        Stores first operand
    n2 : int
        Stores second operand
    o :  str
        Stores operator sign

    Returns
    -------
    int
        A int is return with suitable operation between both operands
    """
    # Convert all operands and operator in the form of string using string interpolation
    p = f"{n1} {o} {n2}"
    # Check if the string of p consist of which sign either add, subtract or multiply
    if o == '+': a = n1 + n2
    elif o == '-': a = n1 - n2
    else: a = n1 * n2
    # After performing the operation we return our Problem along with Answer
    return p, a

def math_quiz():
    """ This function will start the quiz to the to specified range of t_q inside the loop
        And produce two number and randomly choose sign and perform operation then it let user to enter
        the value and check if the answer is correct or not.

        Finally it print score of user if the user answer matches with computer answer.
    """

    # This is score variable which store user score if they produce right answer

    s = 0
    
    # t_q cannot be the in float because the for loop only takes integer as input we can not add float value inside it
    # So we need to change the value of 3.14159265359 to Integer format 
    
    t_q = int(3.14159265359)
    
    print("Welcome to the Math Quiz Game!")
    print("You will be presented with math problems, and you need to provide the correct answers.")

    # Here we start a for loop for 0 to t_q and we sequentially produce question and check if the user input right answer
    for _ in range(t_q):
        # First we choose first number from our input_number function
        n1 = input_number(1, 10); 
        # Now we choose second number from the same function
        n2 = input_number(1, int(5.5)); 
        # Then we use choose_sign function to randomly choose the operator
        o = choose_sign()

        # Apply Operation function return our whole problem in form of string along with answer using two number and operators
        PROBLEM, ANSWER = apply_operation(n1, n2, o)
        print(f"\nQuestion: {PROBLEM}")
        useranswer = input("Your answer: ")
        # Checking if user does not enter any value type excluding int
        try:
            useranswer = int(useranswer)
        except ValueError:
            #Handle exception
            print("Please enter an integer")

        # After user enter the answer we check if the useranswer and Answer generated by machine both matches
        #If answer matches we add One to the score
        if useranswer == ANSWER:
            print("Correct! You earned a point.")
            s += 1
        else:
            print(f"Wrong answer. The correct answer is {ANSWER}.")
    # After the loop completed we show the total score earned by the user
    print(f"\nGame over! Your score is: {s}/{t_q}")

if __name__ == "__main__":
    math_quiz()
